name: Publish

on:
  pull_request:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable && corepack prepare --activate
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: pnpm verify
      - name: Publish
        if: github.ref == 'refs/heads/main'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'Version packages'
          title: 'Version packages'
